# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - uses: manyuanrong/setup-ossutil@v1.0
        with:
          # endpoint 可以去oss控制台上查看
          endpoint: "oss-cn-shanghai.aliyuncs.com"
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
      - name: Deploy To OSS
        run: ossutil cp -rf dist oss://chaos-han-meng/
      # - name: RSyncer Action
      #   uses: Pendect/action-rsyncer@v1.1.0
      #   env:
      #     DEPLOY_KEY: ${{ secrets.chaos_server }}
      #   with:
      #     src: "dist/"
      #     dest: "root@39.97.164.224:/usr/local/services/chaos-han-meng"

      # - name: Deploy
      #   env:
      #     ACTIONS_DEPLOY_KEY: ${{ secrets.chaos_server }}
      #     HOST: 39.97.164.224
      #     USER: root
      #   run: |
      #     echo 'hahaha'


